### ISSUE TITLE
issue with run_docker_build.sh

### ISSUE THREAD

**Issue by Aspard** [openturns/build-agrum#2]
Hello Julien,

I tried to update build-agrum for the tag v0.17.2 but there is an issue with the line `${ARCH}-w64-mingw32-strip --strip-unneeded ${PREFIX}/bin/*.dll ${PREFIX}/Lib/site-packages/*/*.pyd` in the script run_docker_buid.sh.

https://travis-ci.org/github/openturns/build-agrum/jobs/665971117

It seems that the variables PYTHON_INCLUDE_DIR, PYTHON_INSTALL, PYTHON_LIBRARY defined line 254 aren't found (cf line 333-339).

Do you have, by any chance, an idea of how to fix it ?

Hope you're doing fine,

Gaspard

**Comment by jschueller** [comment]
hello, it seems BUILD_PYTHON defaults to OFF now, that's weird:
https://gitlab.com/agrumery/aGrUM/-/commit/27fb335710ff689da5fbc1092a2aaf54098357e5

**Comment by Aspard** [comment]
Indeed, that was it !

Thank you for your help :-)
