### ISSUE TITLE
Python libs and include dirs not found

### ISSUE THREAD

**Issue by Aspard** [openturns/build-agrum#5]
Hello @jschueller,

I tried to update `run_docker_build.sh` in [newact](https://github.com/openturns/build-agrum/blob/newact) (after messing with the master) in order to match the new cmake behavior but didn't managed to get it right (I thought that Python_EXECUTABLE was the only python related parameter needed now).

Do you know the proper cmake call that we should use ?

Thanks in advance !

**Comment by jschueller** [comment]
with mingw specific layout you also need include & libs: the hint is Python_INCLUDE_DIR not Python_INCLUDE_DIR

**Comment by Aspard** [comment]
Oh thanks, it can be a bit confusing sometimes !
